CREATE TABLE IF NOT EXISTS wahlen (
  id INT AUTO_INCREMENT PRIMARY KEY,
  typ ENUM('federal','state','municipal','european','mayoral') NOT NULL,
  ags VARCHAR(20) NOT NULL,
  ags_name VARCHAR(200),
  election_year INT NOT NULL,
  election_date DATE,
  state VARCHAR(5),
  state_name VARCHAR(100),
  county VARCHAR(10),
  eligible_voters INT,
  number_voters INT,
  valid_votes INT,
  invalid_votes INT,
  turnout DECIMAL(8,6),
  cdu_csu DECIMAL(8,6),
  spd DECIMAL(8,6),
  gruene DECIMAL(8,6),
  fdp DECIMAL(8,6),
  linke_pds DECIMAL(8,6),
  afd DECIMAL(8,6),
  bsw DECIMAL(8,6),
  npd DECIMAL(8,6),
  freie_waehler DECIMAL(8,6),
  piraten DECIMAL(8,6),
  die_partei DECIMAL(8,6),
  other DECIMAL(8,6),
  far_right DECIMAL(8,6),
  far_left DECIMAL(8,6),
  winning_party VARCHAR(50),
  winner_party VARCHAR(50),
  winner_voteshare DECIMAL(8,6),
  election_type VARCHAR(50),
  round INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_entry (typ, ags, election_year, election_type, round),
  INDEX idx_typ_year (typ, election_year),
  INDEX idx_ags (ags),
  INDEX idx_state (state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
