CREATE TABLE IF NOT EXISTS world_indicators (
  id INT AUTO_INCREMENT PRIMARY KEY,
  country_code VARCHAR(3) NOT NULL,
  country_name VARCHAR(200),
  region VARCHAR(100),
  income_level VARCHAR(50),
  indicator_code VARCHAR(50) NOT NULL,
  indicator_name VARCHAR(300),
  year INT NOT NULL,
  value DECIMAL(20,6),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_entry (country_code, indicator_code, year),
  INDEX idx_indicator_year (indicator_code, year),
  INDEX idx_country (country_code),
  INDEX idx_region (region)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS world_indicator_meta (
  indicator_code VARCHAR(50) PRIMARY KEY,
  indicator_name VARCHAR(300),
  category VARCHAR(50),
  unit VARCHAR(100),
  description_de TEXT,
  description_en TEXT,
  source VARCHAR(200),
  source_url VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO world_indicator_meta
(indicator_code, indicator_name, category, unit, description_de, description_en, source, source_url) VALUES
('NY.GDP.PCAP.CD', 'GDP per capita (current US$)', 'economy', 'current US$',
 'Bruttoinlandsprodukt pro Kopf in aktuellen US-Dollar.',
 'Gross domestic product per capita in current US dollars.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('NY.GDP.MKTP.KD.ZG', 'GDP growth (annual %)', 'economy', '%',
 'BIP-Wachstum gegenüber dem Vorjahr in Prozent.',
 'Annual percentage growth rate of GDP at constant prices.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('NY.GDP.MKTP.CD', 'GDP (current US$)', 'economy', 'current US$',
 'Bruttoinlandsprodukt in aktuellen US-Dollar.',
 'Gross domestic product in current US dollars.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('FP.CPI.TOTL.ZG', 'Inflation, consumer prices (annual %)', 'economy', '%',
 'Inflation gemessen am Verbraucherpreisindex, jährliche Veränderung in Prozent.',
 'Inflation as measured by the consumer price index, annual percent change.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SL.UEM.TOTL.ZS', 'Unemployment, total (% of labor force)', 'economy', '%',
 'Arbeitslosenquote der Erwerbsbevölkerung in Prozent.',
 'Unemployment as share of the total labor force.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('NE.EXP.GNFS.ZS', 'Exports of goods and services (% of GDP)', 'economy', '%',
 'Exporte von Gütern und Dienstleistungen als Anteil am BIP.',
 'Exports of goods and services as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('BN.CAB.XOKA.GD.ZS', 'Current account balance (% of GDP)', 'economy', '%',
 'Leistungsbilanzsaldo als Anteil am BIP.',
 'Current account balance as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('GC.DOD.TOTL.GD.ZS', 'Central government debt, total (% of GDP)', 'economy', '%',
 'Staatsverschuldung der Zentralregierung als Anteil am BIP.',
 'Central government debt as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('GC.REV.XGRT.GD.ZS', 'Government revenue, excluding grants (% of GDP)', 'economy', '%',
 'Staatseinnahmen ohne Zuschüsse als Anteil am BIP.',
 'Government revenue excluding grants as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.POP.TOTL', 'Population, total', 'population', 'count',
 'Gesamtbevölkerung.',
 'Total population.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.DYN.LE00.IN', 'Life expectancy at birth, total (years)', 'population', 'years',
 'Lebenserwartung bei Geburt in Jahren.',
 'Life expectancy at birth, in years.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.DYN.CBRT.IN', 'Birth rate, crude (per 1,000 people)', 'population', 'per 1,000',
 'Rohe Geburtenrate pro 1.000 Einwohner.',
 'Crude birth rate per 1,000 people.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.DYN.CDRT.IN', 'Death rate, crude (per 1,000 people)', 'population', 'per 1,000',
 'Rohe Sterberate pro 1.000 Einwohner.',
 'Crude death rate per 1,000 people.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.URB.TOTL.IN.ZS', 'Urban population (% of total)', 'population', '%',
 'Städtische Bevölkerung als Anteil der Gesamtbevölkerung.',
 'Urban population as a percentage of total population.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.DYN.TFRT.IN', 'Fertility rate, total (births per woman)', 'population', 'births per woman',
 'Gesamtfruchtbarkeitsrate (Kinder pro Frau).',
 'Total fertility rate, births per woman.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.POP.65UP.TO.ZS', 'Population ages 65 and above (% of total)', 'population', '%',
 'Bevölkerung ab 65 Jahren als Anteil der Gesamtbevölkerung.',
 'Population ages 65 and above as a percentage of total.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SM.POP.NETM', 'Net migration', 'population', 'persons',
 'Nettozuwanderung (Einwanderer minus Auswanderer).',
 'Net migration (immigrants minus emigrants).',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SP.POP.DPND', 'Age dependency ratio (% of working-age population)', 'population', '%',
 'Altersabhängigkeitsquote relativ zur erwerbsfähigen Bevölkerung.',
 'Age dependency ratio as a percentage of working-age population.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SE.ADT.LITR.ZS', 'Literacy rate, adult total (% ages 15+)', 'education', '%',
 'Alphabetisierungsrate der Erwachsenen (15+).',
 'Adult literacy rate, ages 15 and above.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SE.XPD.TOTL.GD.ZS', 'Government expenditure on education, total (% of GDP)', 'education', '%',
 'Staatliche Bildungsausgaben als Anteil am BIP.',
 'Government expenditure on education as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SE.PRM.ENRR', 'School enrollment, primary (% gross)', 'education', '%',
 'Bruttoeinschulungsquote Primarstufe.',
 'Gross enrollment ratio, primary education.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SE.SEC.ENRR', 'School enrollment, secondary (% gross)', 'education', '%',
 'Bruttoeinschulungsquote Sekundarstufe.',
 'Gross enrollment ratio, secondary education.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SH.XPD.CHEX.GD.ZS', 'Current health expenditure (% of GDP)', 'health', '%',
 'Aktuelle Gesundheitsausgaben als Anteil am BIP.',
 'Current health expenditure as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SH.DYN.MORT', 'Mortality rate, under-5 (per 1,000 live births)', 'health', 'per 1,000',
 'Kindersterblichkeit unter 5 Jahren pro 1.000 Lebendgeburten.',
 'Under-five mortality rate per 1,000 live births.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SH.MED.PHYS.ZS', 'Physicians (per 1,000 people)', 'health', 'per 1,000',
 'Ärztinnen und Ärzte pro 1.000 Einwohner.',
 'Physicians per 1,000 people.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SH.STA.MMRT', 'Maternal mortality ratio (per 100,000 live births)', 'health', 'per 100,000',
 'Müttersterblichkeit pro 100.000 Lebendgeburten.',
 'Maternal mortality ratio per 100,000 live births.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SH.H2O.BASW.ZS', 'People using at least basic drinking water services (% of population)', 'health', '%',
 'Anteil der Bevölkerung mit mindestens grundlegendem Zugang zu Trinkwasser.',
 'People using at least basic drinking water services, percentage of population.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('EN.ATM.CO2E.PC', 'CO2 emissions (metric tons per capita)', 'environment', 'metric tons per capita',
 'CO2-Emissionen in Tonnen pro Kopf.',
 'Carbon dioxide emissions in metric tons per capita.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('EG.FEC.RNEW.ZS', 'Renewable energy consumption (% of total final energy consumption)', 'environment', '%',
 'Anteil erneuerbarer Energie am Endenergieverbrauch.',
 'Renewable energy consumption as a percentage of total final energy consumption.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('AG.LND.FRST.ZS', 'Forest area (% of land area)', 'environment', '%',
 'Waldbedeckung als Anteil der Landesfläche.',
 'Forest area as a percentage of land area.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('EG.USE.PCAP.KG.OE', 'Energy use (kg of oil equivalent per capita)', 'environment', 'kg oil eq./capita',
 'Energieverbrauch in kg Öläquivalent pro Kopf.',
 'Energy use in kg of oil equivalent per capita.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('EG.ELC.ACCS.ZS', 'Access to electricity (% of population)', 'environment', '%',
 'Anteil der Bevölkerung mit Zugang zu Elektrizität.',
 'Access to electricity as a percentage of population.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('CC.EST', 'Control of corruption (estimate)', 'governance', 'estimate (-2.5 to 2.5)',
 'Kontrolle von Korruption (Schätzung, WGI).',
 'Control of corruption estimate (WGI).',
 'World Bank WGI', 'https://info.worldbank.org/governance/wgi/'),
('RL.EST', 'Rule of law (estimate)', 'governance', 'estimate (-2.5 to 2.5)',
 'Rechtsstaatlichkeit (Schätzung, WGI).',
 'Rule of law estimate (WGI).',
 'World Bank WGI', 'https://info.worldbank.org/governance/wgi/'),
('GE.EST', 'Government effectiveness (estimate)', 'governance', 'estimate (-2.5 to 2.5)',
 'Regierungseffektivität (Schätzung, WGI).',
 'Government effectiveness estimate (WGI).',
 'World Bank WGI', 'https://info.worldbank.org/governance/wgi/'),
('PV.EST', 'Political stability and absence of violence (estimate)', 'governance', 'estimate (-2.5 to 2.5)',
 'Politische Stabilität und Gewaltfreiheit (Schätzung, WGI).',
 'Political stability and absence of violence estimate (WGI).',
 'World Bank WGI', 'https://info.worldbank.org/governance/wgi/'),
('VA.EST', 'Voice and accountability (estimate)', 'governance', 'estimate (-2.5 to 2.5)',
 'Stimme und Rechenschaftspflicht (Schätzung, WGI).',
 'Voice and accountability estimate (WGI).',
 'World Bank WGI', 'https://info.worldbank.org/governance/wgi/'),
('RQ.EST', 'Regulatory quality (estimate)', 'governance', 'estimate (-2.5 to 2.5)',
 'Regulierungsqualität (Schätzung, WGI).',
 'Regulatory quality estimate (WGI).',
 'World Bank WGI', 'https://info.worldbank.org/governance/wgi/'),
('MS.MIL.XPND.GD.ZS', 'Military expenditure (% of GDP)', 'military', '%',
 'Militärausgaben als Anteil am BIP.',
 'Military expenditure as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('MS.MIL.TOTL.P1', 'Armed forces personnel, total', 'military', 'persons',
 'Angehörige der Streitkräfte (gesamt).',
 'Armed forces personnel, total.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SI.POV.GINI', 'Gini index', 'inequality', 'index',
 'Gini-Koeffizient der Einkommensverteilung.',
 'Gini index of income distribution.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SI.POV.DDAY', 'Poverty headcount ratio at $2.15 a day (2017 PPP) (% of population)', 'inequality', '%',
 'Armutsquote bei 2,15 US$/Tag (2017 KKP).',
 'Poverty headcount at $2.15 a day (2017 PPP), percentage of population.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('SG.GEN.PARL.ZS', 'Proportion of seats held by women in national parliaments (%)', 'inequality', '%',
 'Anteil der Parlamentssitze, die von Frauen gehalten werden.',
 'Proportion of seats held by women in national parliaments.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('IT.NET.USER.ZS', 'Individuals using the Internet (% of population)', 'technology', '%',
 'Anteil der Personen, die das Internet nutzen.',
 'Individuals using the Internet as a percentage of population.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('IT.CEL.SETS.P2', 'Mobile cellular subscriptions (per 100 people)', 'technology', 'per 100',
 'Mobilfunkanschlüsse pro 100 Einwohner.',
 'Mobile cellular subscriptions per 100 people.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('GB.XPD.RSDV.GD.ZS', 'Research and development expenditure (% of GDP)', 'technology', '%',
 'Forschungs- und Entwicklungsausgaben als Anteil am BIP.',
 'Research and development expenditure as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('IP.PAT.RESD', 'Patent applications, residents', 'technology', 'count',
 'Patentanmeldungen von Inländern.',
 'Patent applications by residents.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('BX.KLT.DINV.WD.GD.ZS', 'Foreign direct investment, net inflows (% of GDP)', 'trade', '%',
 'Netto-Direktinvestitionen aus dem Ausland als Anteil am BIP.',
 'Foreign direct investment, net inflows as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('DT.ODA.ODAT.GN.ZS', 'Net ODA received (% of GNI)', 'trade', '%',
 'Netto-Entwicklungshilfe (ODA) bezogen auf das BNE.',
 'Net official development assistance received as a percentage of GNI.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('TG.VAL.TOTL.GD.ZS', 'Trade (% of GDP)', 'trade', '%',
 'Handelsvolumen (Importe und Exporte) als Anteil am BIP.',
 'Trade as a percentage of GDP.',
 'World Bank Open Data', 'https://data.worldbank.org'),
('VC.IHR.PSRC.P5', 'Intentional homicides (per 100,000 people)', 'security', 'per 100,000',
 'Vorsätzliche Tötungsdelikte pro 100.000 Einwohner.',
 'Intentional homicides per 100,000 people.',
 'World Bank Open Data', 'https://data.worldbank.org');
